version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.36.31
    - 1.37.1
    - 1.37.10
    - 1.37.15
    - 1.37.20
    - 1.37.25
    - 1.37.30
    - 1.37.6
    - 1.38.1
    - 1.38.12
    - 1.38.17
    - 1.38.21
    - 1.38.7
  - dependency-name: github.com/aws/aws-lambda-go
    versions:
    - 1.22.0
